### ISSUE TITLE
Compatibility with Xojo Desktop API 2.0

### ISSUE THREAD

**Issue by snus3** [tempelmann/custom-editfield#39]
Usage in an application updated to Xojo Desktop API 2.0 is not possible anymore because of some objects are not compatible with the new controls.

"Quick" try to update the custom-editfield demo project to API 2.0 somehow worked but the edit field is still not fully working.

**Comment by simulanics** [comment]
This is not true. See https://babelfish.studio. - The application uses full use of API 2.0 with no 1.0 references. I will be releasing the updated API 2.0 version of the editor with bug fixes I've added along the way, as well as a myriad of other official API 2.0 code soon for the community. See xojostudio.org. :-)

**Comment by tempelmann** [comment]
Matthew, please use the proper ways and push a branch on the main github so that others can help maintain it. Name the branch API2 or something similar, please.

**Comment by simulanics** [comment]
I will create a new branch and let you know. It's CEF updated for API 2.0. The software at the site was updated and compiled using API 2.0 solely - and features CEF as its primary coding component for HTML, JavaScript, and CSS manipulation. - the CEF control is the most important part of that particular piece of software to function and it's worked flawlessly with the updates.

**Comment by gkjpettet** [comment]
@simulanics Can you please create a new branch with these changes Matthew if you're able to? I am about to update CEF for API 2.0 but then I noticed this issue so I'd rather not reinvent the wheel if I don't have to!

**Comment by simulanics** [comment]
Hello. Apologies for my vacancy. As you know I was wrongfully banned from the Xojo community by Alyssa Foley in 2022, for what she stated were lies before the community, and is now deemed defamation of character as we've proved her wrong and have mounds of evidence, which is why they cannot say one iota for me even speaking out and haven't even tried; not even on social media ,😂. Guess they just keep kind of hoping I'll back down; I NEVER DO. They will be aged and dead long before that happens. 🤗 She knows I have her cornered, so she refuses to even comment to me now. She actually called me a liar PUBLICLY for a direct conversation that occurred between Geoff and I directly; that was also recorded "for quality assurance." 😉 Guess she thought she was a "know-it-all", and refused to accept that she was wrong. How childish right? Accountability and integrity are part of being an adult. Upon asking her about it, she said I had 3 "hits" against me, thus the ban, but kept repeating herself for the only single incident by her, and even snippeted it as an image to me -3 times - not joking. So she was just lying and being hateful to me. When I called her out on that, she cowered and hid from accountability/adulting. So, I'm working on that a bit, and had been seeking peaceful resolutions, but haven't heard much back, so maybe even might push for a class action if they don't start seeing the light, with some other members over at ifnotnil. Statements have already been gathered from MANY individuals.🤗 Xojo/Alyssa keep hoping time is their friend, when in reality it is their enemy, and allowing more ammunition and stories to all come together that only raise the flood waters they'll have to navigate. A simple public apology would make it all go away, but this will be a valuable lesson in why being overly prideful is destructive, and why all people deserve to be treated with respect. 💯

But, I actually have all sorts of free code over at xojostudio.org, hundreds of controls and classes all written for API 2.0, with documentation for each item, it's just been hidden so only legit developers, and not Xojo cronies, are benefiting from my hard works! 😀

I do not have access to my git from my phone, but the download link for CustomEditField 2.0 is at:

https://www.xojostudio.org/download/xds-customeditfield2023r1-api2-0/?wpdmdl=14843&masterkey=HDjyhcZj9yUaGWKa5CVt_IY4G9xqL7niTvcoCv-XT3Qa9xLcEF4g5hwbwUKqBD7kqx9j4-BwsuvPOXeKhESy-lr8DD_D-IKszczzroyCzLc

You're welcome to download and post to GitHub if you'd like. I won't have time anytime soon, even though I do maintain and update the code through the site (it's automated when I save any of the projects - they auto upload to the website). I'm still out about 60 days before I let the furies of hell pour upon Xojo and able to see if I can reconnect with the community to help try to build it up, or if we need to push to "burn it all down" and see what rises from the ashes - if anything. I've been far too nice with them, for far too long, only because I've been a Xojo developer for going on 23 years, and had great respect for Geoff, that is quickly waning. I wanted to resolve the issue "the way normal adults would." But... When the left arm becomes malignant, you can cut it off, or die with it. 🤗 and all I asked her for was a public apology for her wrongful words and actions (she didn't have a problem calling me a liar PUBLICLY!), to remove her defaming posts about me, and to reinstate my account. But - she has no integrity. Children cannot admit when they are wrong, so she'll be treated like a child if need be. The leverage is that when it comes down to Xojo or her, who is Xojo going to preserve? Xojo didn't technically do anything wrong - Alyssa did, and she represents Xojo, but she is the one ultimately who should be accountable for her actions, not Xojo. But we'll 🙈🙉🙊 The difference between her public statements and mine... Mine are 100% true 😀, so they can't do nada about it.

Where I've been last few months  **I cut a finger off (right pinky at middle knuckle) and severed tendons in ring finger and part of hand on March 13th on a razor sharp rail... All sewn back together, but attending physical therapy 3x/WK to relearn to use it since about a week after surgery. So I've still been developing for contracts and such still, just a bit more hectic doing it all single/left handed. Just landed another govt contract recently -AI based forensics.🤘 and starting on a multi-million/billion dollar AI project with a team of 14 other individuals scattered across the globe in 12 days 🙌 super psyched for that endeavor. 

Figured I'd let y'all know! mcombatti@xojostudio.org is always best place to reach me for anything Xojo related. I try to keep groups separate by email. Thanks for tagging me so I received the request immediately here thru Github notifications! You can remove this post after downloading source code, just wanted to explain my extreme silence and what's cooking 😀

**Comment by gkjpettet** [comment]
Thanks for the file Matthew. Sorry to hear you've been through a tough time.

There seems to be a single compilation error in `TextLine.Paint()` (line 118):

```xojo
g.DrawText xt, x, y
```

There is no variable named `xt` so I'm not sure what string you're trying to draw here.

**Comment by simulanics** [comment]
That may be a straggler that can be commented out, without looking directly at the code; I'll take a look and re-save the project here in just a bit this evening - take all but 10 minutes to fire up the Mac and check. It was last altered on a Windows machine, so I'm almost certain that was a Mac leftover that can commented out, that the compiler wouldn't have recognized building on Windows. Give me just a bit and I'll have an answer for you on what I did 😀. Oddly I've built it into the BabelFish Studio IDE without any debug errors, as is, so I'm super curious to get home to my computer to see custom edit stand-alone on Mac to see what's up. 🤔. Give me a bit and I'll return. Hope your day has been well!

Here's some other code access that I need to get Githubbed as well. 

https://www.xojostudio.org/?cmp_bypass=XDSAlphaRelease2023r1

Happy coding!

**Comment by gkjpettet** [comment]
Spot on Matthew - that's got it up and running.

Lovely job on updating the control. I haven't dug into it but the only issue I've noticed is that pressing tab to display the autocomplete popup window causes the popup window to flash momentarily but it essentially doesn't work. Try typing `someKey.s` for example and press tab...

**Comment by simulanics** [comment]
> Spot on Matthew - that's got it up and running.
> 
> Lovely job on updating the control. I haven't dug into it but the only issue I've noticed is that pressing tab to display the autocomplete popup window causes the popup window to flash momentarily but it essentially doesn't work. Try typing `someKey.s` for example and press tab...


I will delve into this tomorrow and take a peek after an AI conference call from 11-1. Under the key press event, I may have set it to mimic VSCode by using Shift+space combo to invoke auto competition (at least I did in BF Studio). If that's the case, I should've commented out the chr(9) line under the key press event, and you may be able to swap the // comment lines. I'll look and get back with you soon. Have a great evening!

**Comment by gkjpettet** [comment]
You might want to consider closing this issue since I have released an open source almost feature-complete port of CEF up and running that is fully API 2.0 compliant - [SyntaxArea.](https://github.com/gkjpettet/SyntaxArea)

**Comment by tempelmann** [comment]
Okay. Why did you not post it as a branch for CEF, though? This makes it harder for people to find the new one. I'll add a link to it on the main page, though.

**Comment by gkjpettet** [comment]
It’s a complete rewrite but I had the code for CEF available to inspect to help me. 

I rewrote it because there are design changes with the API that I wanted to make that didn’t fit with tweaking CEF.
