### ISSUE TITLE
Highlight definition startRegEx doesn't match if regex begins with whitespace

### ISSUE THREAD

**Issue by gkjpettet** [tempelmann/custom-editfield#40]
I'm trying to write a Markdown highlight definition for the CustomEditfield. Unless I'm misunderstanding, I think I have found a bug in the highlight engine.

This is a really simple definition that should highlight text flanked with `__`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<highlightDefinition version="1.0">
	<name>Markdown</name>
	
	<contexts defaultColor="#000000" caseSensitive="no">		
		<highlightContext name="BoldUnderscore" highlightColor="#326510">
			<startRegEx>\s__[^ \t]</startRegEx>
			<endRegEx>__</endRegEx>
		</highlightContext>
	</contexts>
	
</highlightDefinition>
```

Note that the context should begin with a `__` that is preceded by whitespace with at least one non-space or non-tab character. This fails to work on this text:

`a __bold__`

which it should. If I remove `\s` and replace it with `[ ]`, same thing. If I change the regex to `__[^ \t]` then it highlights the `bold` text but this is an incorrect pattern as I need to assert that there is whitespace before the `__`.

I've looked through the code of CustomEditfield to make sure that the engine isn't trimming spaces between matches but I don't think it is.

Am I misunderstanding something here?a

I've also posted this on the Xojo forums as I'm not sure how active this repo is anymore:

https://forum.xojo.com/t/regex-question-regarding-a-customeditfield-definition/74183

**Comment by tempelmann** [comment]
The issue is that `HighlightDefinition.Constructor` silently adds a rule for detecting whitespace to the context rules, and this precedes all other rules.
The fix is to add the blank-check rule to the end of the context checks.
Since I have no understanding whether this may break other highlight definitions, I've introduced an optional parameter to the Constructor `fixIssue40` that defgaults to `true`. With that, the blank check will be added as the last rule, while developers who suspect this to cause problems with existing definitions can revert it easily.

**Comment by gkjpettet** [comment]
Thanks. I think this can be closed now.
